version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - wal_level=logical

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres: