logging:
  level:
    com.example.store: INFO
    org.hibernate.SQL: INFO

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

springdoc:
  swagger-ui:
    enabled: false