spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master-test.yaml
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG # Logs SQL queries
    org.hibernate.type.descriptor.sql: TRACE # Logs prepared statement parameters (values)