spring:
  profiles:
    # unless overridden by the SPRING_PROFILES_ACTIVE environment variable.
    default: dev
    # The 'dev' profile is active by default unless overridden (e.g., by 'test' or 'prod').
    active:
      - dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/store}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 60000 # 1 minute
      connection-timeout: 15000 # Fail faster (15 seconds)
      max-lifetime: 300000 # Retire connections after 5 minutes to prevent staleness
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
        generate_statistics: true
        # --- L2 Cache Configuration ---
        # 1. Enable the second-level cache
        cache.use_second_level_cache: true
        # 2. Specify the JCache region factory
        cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        # 3. Specify the JCache provider (Ehcache)
        javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      # --- Standard JPA Caching ---
      # 4. IMPORTANT: This ensures only entities explicitly marked with @Cacheable are cached.
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#logging:
#  level:
#    org.hibernate.SQL: DEBUG # Logs SQL queries
#    org.hibernate.type.descriptor.sql: TRACE # Logs prepared statement parameters (values)

springdoc:
  swagger-ui:
    # static OpenAPI.yaml file we placed in the resources/static folder.
    url: /OpenAPI.yaml
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,liquibase,prometheus,beans"
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
