apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app-deployment
  namespace: prod
  labels:
    app: store-app
spec:
  replicas: 2 # Run 2 instances for availability
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
        - name: store-app
          image: ghcr.io/optimusprimelogan/store:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
                # Use environment variables sourced from the secret created by CloudNativePG.
                # This decouples your application from the database credentials.
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: store-postgres-db-app # Secret created by CNPG
                  key: jdbc-uri # CNPG provides a ready-to-use JDBC URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: store-postgres-db-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-postgres-db-app
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
          # Set resource requests and limits for stable performance
          resources:
            requests:
              cpu: "250m" # 0.25 CPU core
              memory: "512Mi"
            limits:
              cpu: "1" # 1 CPU core
              memory: "1Gi"
