apiVersion: v1
kind: Service
metadata:
  name: store-app-svc
  namespace: prod
  labels:
    app: store-app
  # This tells Prometheus to scrape this service.
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "http"
spec:
  type: NodePort
  selector:
    app: store-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080