apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: prod
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-db
  # This makes it a "headless" service, used by the StatefulSet
  clusterIP: None