apiVersion: v1
kind: Secret
metadata:
  name: store-app-secret
  namespace: prod
type: Opaque
data:
  # These keys must match the environment variables your app expects: DB_USER, DB_PASSWORD
  # We are reusing the values from the main postgres-secret
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4=