apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          # Scrape only services that have the 'prometheus.io/scrape: true' annotation.
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Use the 'prometheus.io/path' annotation for the metrics path.
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Use the 'prometheus.io/port' annotation to construct the address.
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          # Use the service's namespace as a label.
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          # Use the service's name as the instance label.
          - source_labels: [__meta_kubernetes_service_name]
            target_label: instance